---
# Create a text file representing three VLANs including vlan names to add onto an
# Arista switch. Perform a NAPALM merge operation to push this configuration
# change. Manually check the diff file before performing the commit.

- name: NAPALM vlan configuration
  hosts: pynet-sw1
  gather_facts: False
  tasks:
    - napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: eos
        config_file: pynet-sw1-merge.cfg
        commit_changes: True
        replace_config: False
        diff_file: "{{ inventory_hostname }}.diff"
        get_diffs: True

