---
- name: NAPALM gather information on EOS
  hosts: pynet-sw1
  tasks:
    - name: Gather information
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: eos
        filter: [facts, interfaces, bgp_neighbors]
      register: result
      tags: facts

    - name: Debuggging
      debug: var=result
      tags: facts

- name: NAPALM vlan configuration
  hosts: pynet-sw1
  tasks:
    - napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: eos
        config_file: pynet-sw1-merge.cfg
        commit_changes: True
        replace_config: False
        get_diffs: True
        diff_file: "DIFFS/{{ inventory_hostname }}.diff"
      tags: config
